version: '2'
services:
  frontend:
    build: ./frontend
    env_file: ./frontend/config.env
    ports:
     - "80:80"
    volumes:
            - ./frontend/app:/app
  backend:
    build: ./backend
    ports:
     - "8080:8080"
    volumes:
            - ./backend/app:/app
