version: '2'
services:
  frontend:
    build: ./frontend
    env_file: ./frontend/config.env
    expose:
            - "80"
    volumes:
            - ./frontend/app:/app
  backend:
    build: ./backend
    expose:
            - "8080"
    volumes:
            - ./backend/app:/app
  nginx:
    build: ./nginx
    links:
        - frontend:frontend
        - backend:backend
    ports:
        - "8080:80"

