version: '2'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile-prod
    env_file: ./frontend/config.env
    expose:
            - "80"
  backend:
    build: ./backend
    expose:
            - "8080"
    volumes:
            - ./backend/app:/app
  nginx:
    build: ./nginx
    links:
        - frontend:frontend
        - backend:backend
    ports:
        - "80:80"

  redis:
    image: "redis:alpine"

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
        #uncoment for prod when ram is ok 
        #      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#uncoment for prod when ram is ok 
#    mem_limit: 1G
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
            - "9200:9200"

#uncoment for more nodes
#  elasticsearch2:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
#    environment:
#      - cluster.name=docker-cluster
#        #      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
#      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    #    mem_limit: 1G 
#    volumes:
#      - esdata2:/usr/share/elasticsearch/data

volumes:
  esdata1:
    driver: local
#uncoment for more nodes
#  esdata2:
#    driver: local

