version: '2'
services:
  frontend:
    build: ./frontend
    dockerfile: Dockerfile-prod
    env_file: ./frontend/config.env
    expose:
            - "80"
  backend:
    build: ./backend
    expose:
            - "8080"
    volumes:
            - ./backend/app:/app
  nginx:
    build: ./nginx
    links:
        - frontend:frontend
        - backend:backend
    ports:
        - "80:80"

  redis:
    image: "redis:alpine"
